# 7thgenaccy.properties
#
# Default properties for the jmri.jmrix.loconet.accy7thgen package

FINDLABEL = Find 7th-gen. Devices

FOOTNOTEASE74 * All SE74 devices implement Turnouts 1021-1024, and 2041-2044 for fixed 'broadcast' addresses.
FOOTNOTEBSE74 ** SE74 devices, when in Aspect mode, implement Head 2048 as a fixed "broadcast" address.
FOOTNOTEPM74 *** PM74 devices may not provide "Reporter" functionality for certain 'Base Address'es.
FOOTNOTEGENERAL ^^^^ Turnout addresses 2041 thru 2044 are used for the LocoNet "Interrogate" operations. 

INFONOTICETEXT  <html>The Digitrax Seventh-generation Accessory tool is still under development. \
<p><p>It is provided to give a usable method for changing a Digitrax Seventh-generation \
<p>Accessory device's 'Base Address'.  This feature seems to be fully-functional. \
<p><p>It is also an <em>unproven</em> method to help users determine the types of LocoNet \
<p>messages and their addresses for each type of Digitrax Seventh-generation \
<p>accessory device seen on the LocoNet connection. \
<p><p>This message will be <em>removed</em> from this tool when these features have been \
<p>proven.
